Repository qld-gov-au/qgds-bootstrap5, pull requests merged in 2024-06, with the labels that each got.

#195 [QOLOE-198] Handling js error when breadcrumb component does not exist.
  src/components/bs5/breadcrumbs/breadcrumb.functions.js
  src/main.js
Labels: bug

#186 QOLOE-172 Decreasing underline offset for small tags
  src/components/bs5/tag/tag.scss
Labels: enhancement

#197 Readme update post repo name change
  .github/workflows/compile.js.yml
  README.md
  binary-repo/README.md
  package.json
Labels: documentation

#191 [QOLOE-175]Update Callout spacer - based on Design QA feedback.
  src/components/bs5/callout/callout.scss
Labels: bug

#206 Correct Dependabot version rollup so that there is less PR's open for…
  .github/dependabot.yml
Labels: enhancement

#207 WIP: QOLOE-209 QUICK EXIT Design change for Forgov
  package-lock.json
  src/components/bs5/quickexit/_colours.scss
  src/components/bs5/quickexit/quickexit.data.json
  src/components/bs5/quickexit/quickexit.hbs
  src/components/bs5/quickexit/quickexit.scss
  src/components/bs5/quickexit/quickexit.stories.js
Labels: enhancement

#171 QOLOE-120 Enhancements
  src/components/bs5/header/_colours.scss
  src/components/bs5/header/header.data.json
  src/components/bs5/header/header.functions.js
  src/components/bs5/header/header.hbs
  src/components/bs5/header/header.scss
  src/components/bs5/header/header.stories.js
  src/components/bs5/navbar/_colours.scss
  src/components/bs5/navbar/navbar.data.json
  src/components/bs5/navbar/navbar.hbs
  src/components/bs5/navbar/navbar.scss
  src/components/bs5/searchInput/_colours.scss
  src/components/bs5/searchInput/search.functions.js
  src/components/bs5/searchInput/search.json
  src/components/bs5/searchInput/searchInput.data.json
  src/components/bs5/searchInput/searchInput.hbs
  src/components/bs5/searchInput/searchInput.scss
  src/components/bs5/searchInput/searchInput.stories.js
  src/components/common/header/Header.js
  src/components/common/header/header.html
  src/components/common/header/header.scss
  src/js/handlebars.helpers.js
  src/main.js
  src/scss/qld-variables.scss
Labels: bug, documentation, enhancement

#130 WIP: Footer - Sen's updates
  src/components/bs5/footer/_colours.scss
  src/components/bs5/footer/_measurements.scss
  src/components/bs5/footer/footer.data.json
  src/components/bs5/footer/footer.functions.js
  src/components/bs5/footer/footer.hbs
  src/components/bs5/footer/footer.scss
  src/components/bs5/footer/footer.stories.js
  src/components/bs5/footer/footerForgov.hbs
  src/main.js
  src/scss/qld-type.scss
  src/templates/compiled/index.html
  src/templates/index.html
Labels: enhancement

#214 QOLOE-171 Typography New QA Branch
  src/components/bs5/sidenav/sidenav.scss
  src/components/bs5/typography/typography.scss
  src/components/bs5/typography/typography.stories.js
  src/scss/qld-type.scss
Labels: bug

#223 [QOLOE-172] Add Status tag
  src/components/bs5/tag/tag.data.json
  src/components/bs5/tag/tag.hbs
  src/components/bs5/tag/tag.scss
  src/components/bs5/tag/tag.stories.js
Labels: enhancement

#180 QOLOE-22 Customising gutter value
  src/components/bs5/footer/footer.scss
  src/components/common/layout/content.scss
Labels: bug, enhancement

#216 QOLOE 120 Enhancements
  src/assets/img/endorsed.svg
  src/components/bs5/header/header.data.json
  src/components/bs5/header/header.functions.js
  src/components/bs5/header/header.hbs
  src/components/bs5/header/header.scss
  src/components/bs5/header/header.stories.js
  src/components/bs5/navbar/navbar.data.json
  src/components/bs5/navbar/navbar.functions.js
  src/components/bs5/navbar/navbar.hbs
  src/components/bs5/navbar/navbar.scss
  src/components/bs5/searchInput/search.functions.js
  src/main.js
  src/scss/qld-type.scss
Labels: bug, enhancement

#234 [QOLOE-201]Update Video based on Design QA and minor scss tidy up.
  src/components/bs5/video/video.scss
Labels: bug

#225 BUG: QOLOE-263 Updated CSS
  src/components/bs5/accordion/accordion.scss
Labels: bug

#228 QOLOE-271 CSS Changes
  src/components/bs5/spinner/spinner.scss
Labels: bug

#237 QOLOE-22-Footer-removed all handlebars comments
  src/components/bs5/footer/footer.data.json
  src/components/bs5/footer/footer.functions.js
  src/components/bs5/footer/footer.hbs
  src/components/bs5/footer/footerForgov.hbs
Labels: bug

#222 QOLOE-174 Fixing up card feature and arrow structure and style
  src/components/bs5/card/card.hbs
  src/components/bs5/card/card.scss
Labels: bug, enhancement

#227 QOLOE-184 Inpage alert QA
  src/components/bs5/inpageAlert/inpageAlert.scss
Labels: bug

#233 [QOLOE-173] Fix buttons style - Design QA
  src/components/bs5/button/button.hbs
  src/components/bs5/button/button.scss
  src/components/bs5/button/button.stories.js
Labels: bug

#254 QOLOE-125 Add head meta elements which will include replaced version details in dist,
  .esbuild/plugins/qgds-plugin-version.js
  esbuild.js
  src/components/bs5/breadcrumbs/breadcrumbs.stories.js
  src/components/bs5/button/button.stories.js
  src/components/bs5/dateinput/Dateinput.stories.js
  src/components/bs5/footer/footer.stories.js
  src/components/bs5/formcheck/_formcheck.stories.bak.js
  src/components/bs5/formcheck/stories/checkbox/checkbox.stories.js
  src/components/bs5/formcheck/stories/radio/radio.stories.js
  src/components/bs5/head/Head.js
  src/components/bs5/head/head.data.json
  src/components/bs5/head/head.hbs
  src/components/bs5/head/head.stories.js
  src/components/bs5/head/manifest.json
  src/components/bs5/header/header.stories.js
  src/components/bs5/select/Select.stories.js
  src/components/bs5/sidenav/sidenav.stories.js
  src/components/bs5/textarea/Textarea.stories.js
  src/components/bs5/textbox/Textbox.stories.js
Labels: enhancement

#245 QOLOE-22-Footer Updated the CSS Colour Token Values and CSS spacings
  src/components/bs5/footer/_colours.scss
  src/components/bs5/footer/footer.data.json
  src/components/bs5/footer/footer.functions.js
  src/components/bs5/footer/footer.scss
  src/components/bs5/footer/footer.stories.js
Labels: bug

#268 QOLOE-304 Fixing navbar handlebar to render form content
  src/components/bs5/navbar/navbar.hbs
Labels: bug

#269 QOLOE-125 CICD setup for CDN deployment via Release Binary Repo
  .binary-repo/.github/aws/README.md
  .binary-repo/.github/aws/example_cloudfront.cfn.yml
  .binary-repo/.github/aws/iam.cfn.yml
  .binary-repo/.github/aws/setup_github_environment.sh
  .binary-repo/.github/workflows/README.md
  .binary-repo/.github/workflows/cdnAWSDeployment.yml
  .binary-repo/.github/workflows/cdnAWSManualOrRollBack.yml
  .binary-repo/.github/workflows/cdnDeploy.sh
  .binary-repo/.github/workflows/getVersionDetails.sh
  .binary-repo/README.md
  .github/workflows/compile.js.yml
  .github/workflows/release.yml
Labels: enhancement

#265 QOLOE-194 Table component - resolves design QA with CSS updates
  src/components/bs5/table/table.scss
Labels: bug

#283 WIP: Update to allow forgov admin to set suggestions/default search state in Matrix
  src/components/bs5/header/header.stories.js
  src/components/bs5/searchInput/search.functions.js
  src/components/bs5/searchInput/search.json
  src/components/bs5/searchInput/searchInput.data.json
  src/components/bs5/searchInput/searchInput.hbs
Labels: bug

#282 QOLOE-187 Focus within state for action tags
  src/components/bs5/tag/tag.scss
Labels: enhancement

#271 [QOLOE-216] Banner design QA
  .storybook/preview.js
  src/components/bs5/banner/banner.hbs
  src/components/bs5/banner/banner.scss
  src/components/bs5/breadcrumbs/breadcrumbs.scss
Labels: bug

#295 [QOLOE-268] Set responsive width on header's dropdown menu.
  src/components/bs5/navbar/_icons.scss
  src/components/bs5/navbar/navbar.hbs
  src/components/bs5/navbar/navbar.scss
Labels: bug

#287 QOLOE-209 CSS clean up
  src/components/bs5/quickexit/quickexit.scss
Labels: bug

#279 QOLOE-222 Footer component changes
  src/components/bs5/footer/_colours.scss
  src/components/bs5/footer/_measurements.scss
  src/components/bs5/footer/footer.data.json
  src/components/bs5/footer/footer.scss
Labels: bug

#301 [QOLOE-134] Various UATs
  .esbuild/plugins/qgds-plugin-clean-output-folders.js
  .storybook/main.js
  package.json
  src/components/bs5/textbox/textInput.scss
  src/components/bs5/video/video.hbs
Labels: bug, enhancement

#300 Qoloe 222 formio thankyou page
  src/components/bs5/footer/footer.scss
Labels: bug

#261 [QOLOE-197] Update text and textarea inputs styling - Design QA.
  src/components/bs5/textbox/textInput.scss
  src/scss/qld-variables.scss
Labels: bug

#304 QOLOE-222 formIO Radio btn and validation fixs
  src/components/bs5/footer/footer.data.json
  src/components/bs5/footer/footer.scss
Labels: bug

#317 QOLOE-205 Updated the blockquote Visual styling and Padding
  src/components/bs5/blockquote/blockquote.scss
Labels: bug

#323 QOLOE-200 updated the deep page breadcrumb style
  src/components/bs5/breadcrumbs/breadcrumbs.scss
Labels: bug
