Repository qld-gov-au/qgds-bootstrap5, pull requests merged in 2025-09, with the labels that each got.

#763 Qgds 184 footer component changes
  src/components/bs5/footer/Footer.js
  src/components/bs5/footer/_colours.scss
  src/components/bs5/footer/_measurements.scss
  src/components/bs5/footer/customLinks.hbs
  src/components/bs5/footer/feedbackForm.hbs
  src/components/bs5/footer/followLinks.hbs
  src/components/bs5/footer/footer.data.json
  src/components/bs5/footer/footer.functions.js
  src/components/bs5/footer/footer.hbs
  src/components/bs5/footer/footer.scss
  src/components/bs5/footer/footer.stories.js
  src/components/bs5/footer/footerForgov.hbs
  src/components/bs5/footer/footer_formio.scss
  src/js/handlebars.partials.js
  src/js/qld.bootstrap.js
Labels: Major

#786 Fix: Tabs layout changes after design review
  src/components/bs5/tabs/tabs.scss
Labels: bug

#785 QGDS-273 fix icon
  prettier.json
  src/components/bs5/button/button.scss
  src/components/bs5/card/card.scss
  src/components/bs5/footer/footer.scss
  src/components/bs5/globalAlert/globalAlert.scss
  src/components/bs5/icons/Icons.mdx
  src/components/bs5/icons/_icons.sizes.scss
  src/components/bs5/icons/icons.scss
  src/components/bs5/icons/icons.stories.js
  src/components/bs5/icons/mdx/_IconsSizes.mdx
  src/components/bs5/icons/stories/storyFlexContainer.html
  src/components/bs5/icons/stories/storyInlineWithText.html
  src/components/bs5/icons/stories/storySizes.html
  src/components/bs5/icons/story-icon-sizing.html
  src/components/bs5/icons/story-icon-usage.html
  src/components/bs5/link/link.scss
  src/components/bs5/quickexit/quickexit.hbs
  src/components/bs5/quickexit/quickexit.scss
  src/css/functions/_index.scss
  src/css/functions/in-list.scss
  src/css/mixins/_index.scss
  src/css/mixins/make-icon.scss
  src/css/qld-variables.scss
  src/js/handlebars.partials.js
Labels: bug, documentation, enhancement

#797 QGDS-277 Fix: Navbar update based upon design reviews
  src/components/bs5/navbar/navbar.data.json
  src/components/bs5/navbar/navbar.hbs
  src/components/bs5/navbar/navbar.scss
  src/components/bs5/navbar/navbar.stories.js
Labels: bug
